# Generated by Django 5.1 on 2024-08-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/')),
            ],
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='user',
            new_name='uid',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
