# Generated by Django 5.1 on 2024-09-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_users_rename_user_comments_uid_rename_user_posts_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='dislikes',
        ),
    ]
