# Generated by Django 5.1 on 2024-09-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_remove_posts_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
